# Generated by Django 3.0.1 on 2020-01-02 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('79dff7f1-eee2-4469-aed5-51f0c8d8d2b4'), max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
