# Generated by Django 3.0.2 on 2020-01-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20200102_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='uid',
        ),
        migrations.AddField(
            model_name='branch',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
